### ISSUE TITLE
JavaFX issue arising one one machine but not on another

### ISSUE THREAD

**Issue by orsjb** [orsjb/HappyBrackets#13]
This came up on one Mac running El Capitan and Java 8, but not on another machine. It was caused whilst running CodeTask1_1 or 1_2 or the HelloWorld file. one of the early code tasks.

Exception in thread "Thread-7" java.lang.IllegalStateException: Not on FX application thread; currentThread = Thread-7
    at com.sun.javafx.tk.Toolkit.checkFxUserThread(Toolkit.java:204)
    at com.sun.javafx.tk.quantum.QuantumToolkit.checkFxUserThread(QuantumToolkit.java:364)
    at javafx.scene.Scene.addToDirtyList(Scene.java:485)
    at javafx.scene.Node.addToSceneDirtyList(Node.java:424)
    at javafx.scene.Node.impl_markDirty(Node.java:415)
    at javafx.scene.canvas.Canvas.getBuffer(Canvas.java:116)
    at javafx.scene.canvas.GraphicsContext.getBuffer(GraphicsContext.java:593)
    at javafx.scene.canvas.GraphicsContext.reset(GraphicsContext.java:794)
    at javafx.scene.canvas.GraphicsContext.resetIfCovers(GraphicsContext.java:843)
    at javafx.scene.canvas.GraphicsContext.clearRect(GraphicsContext.java:2156)
    at net.happybrackets.controller.gui.WaveformVisualiser$2.run(WaveformVisualiser.java:52)

**Comment by orsjb** [comment]
Resolved. Have to be very careful which Java you're using: OpenJDK, Oracle Java, IntelliJ Java (is this OpenJDK?). Needs to be Oracle :-(
