### ISSUE TITLE
Invalid Classes Cause HB to crash and not recover

### ISSUE THREAD

**Issue by angelofraietta** [orsjb/HappyBrackets#44]
When downloading an invalid class or class is not found, HB crashes and cannot recover, requiring a reboot

**Comment by angelofraietta** [comment]
You can recreate error by disabling encryption on device side. This will allow the exception to be thrown - we need to make a handler for it 

Exception in thread "Thread-4" java.lang.ClassFormatError: Incompatible magic value 3300556053 in class file <Unknown>
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at java.lang.ClassLoader.defineClass(Unknown Source)
        at net.happybrackets.device.dynamic.DynamicClassLoader.createNewClass(DynamicClassLoader.java:31)
        at net.happybrackets.device.HB$2.run(HB.java:460)

**Comment by angelofraietta** [comment]
This has been repaired now in 1.13.5
