### ISSUE TITLE
Bad Sensor Causes Log to fail

### ISSUE THREAD

**Issue by angelofraietta** [orsjb/HappyBrackets#48]
When loading a sensor that does not exist, the Logging for the device stops sending back data
Add this to your sketch on a device with no LSM9DS1

LSM9DS1 mySensor = (LSM9DS1) hb.getSensor(LSM9DS1.class);

If you do this when log is enabled, you see an exception
Looking at the actual log on the PI itself  shows that it throws an exception

When you start looking at log on PI, it goes on forever and fills up disk. The logger is probably getting killed by size. We need to see why we are continually trying to load sensor when we have an exception.

22:25:05,583 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@fe5c40 - Added status listener of type [ch.qos.logback.core.status.OnConsoleStatusListener]
22:25:08,896 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@fe5c40 - About to instantiate appender of type [ch.qos.logback.core.ConsoleAppender]
22:25:08,906 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@fe5c40 - Naming appender as [STDOUT]
22:25:09,617 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@fe5c40 - Setting level of logger [ROOT] to ERROR
22:25:09,682 |-INFO in ch.qos.logback.classic.gaffer.ConfigurationDelegate@fe5c40 - Attaching appender named [STDOUT] to Logger[ROOT]
************************************************************
************************************************************
************************************************************
***            HappyBrackets Version 1.15.4.0            ***
************************************************************
************************************************************
************************************************************
.....JavaSoundAudioIO: Chosen mixer is ALSA [default].
Version sent 1.15.4.0 to port 62586
Version sent 1.15.4.0 to port 59471
Version sent 1.15.4.0 to port 59350
ERROR net.happybrackets.device.sensors.LSM9DS1 - Unable to read to I2C device
java.io.IOException: Error writing to /dev/i2c-1 at address 0x6a. Got -20001.
	at com.pi4j.io.i2c.impl.I2CDeviceImpl.write(I2CDeviceImpl.java:81)
	at net.happybrackets.device.sensors.LSM9DS1.read(LSM9DS1.java:301)
	at net.happybrackets.device.sensors.LSM9DS1.disableAccelerometer(LSM9DS1.java:558)
	at net.happybrackets.device.sensors.LSM9DS1.enableAccelerometer(LSM9DS1.java:541)
	at net.happybrackets.device.sensors.LSM9DS1.<init>(LSM9DS1.java:256)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at net.happybrackets.device.HB.getSensor(HB.java:717)
	at net.happybrackets.develop.DeviceMonitor.AcelerometerSend.action(AcelerometerSend.java:68)
	at net.happybrackets.device.HB$3.run(HB.java:675)
ERROR net.happybrackets.device.sensors.LSM9DS1 - Unable to write to I2C device
java.io.IOException: Error writing to /dev/i2c-1 at address 0x6a to address 0x20. Got -20001.
	at com.pi4j.io.i2c.impl.I2CDeviceImpl.write(I2CDeviceImpl.java:147)
	at net.happybrackets.device.sensors.LSM9DS1.write(LSM9DS1.java:343)
	at net.happybrackets.device.sensors.LSM9DS1.disableAccelerometer(LSM9DS1.java:561)
	at net.happybrackets.device.sensors.LSM9DS1.enableAccelerometer(LSM9DS1.java:541)
	at net.happybrackets.device.sensors.LSM9DS1.<init>(LSM9DS1.java:256)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at net.happybrackets.device.HB.getSensor(HB.java:717)
	at net.happybrackets.develop.DeviceMonitor.AcelerometerSend.action(AcelerometerSend.java:68)
	at net.happybrackets.device.HB$3.run(HB.java:675)
ACCTest 0 0 reg 32 value 123
ERROR net.happybrackets.device.sensors.LSM9DS1 - Unable to write to I2C device
java.io.IOException: Error writing to /dev/i2c-1 at address 0x6a to address 0x20. Got -20001.
	at com.pi4j.io.i2c.impl.I2CDeviceImpl.write(I2CDeviceImpl.java:124)
	at net.happybrackets.device.sensors.LSM9DS1.write(LSM9DS1.java:324)
	at net.happybrackets.device.sensors.LSM9DS1.enableAccelerometer(LSM9DS1.java:544)
	at net.happybrackets.device.sensors.LSM9DS1.<init>(LSM9DS1.java:256)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at net.happybrackets.device.HB.getSensor(HB.java:717)
	at net.happybrackets.develop.DeviceMonitor.AcelerometerSend.action(AcelerometerSend.java:68)
	at net.happybrackets.device.HB$3.run(HB.java:675)
ERROR net.happybrackets.device.sensors.LSM9DS1 - Unable to read to I2C device
java.io.IOException: Error writing to /dev/i2c-1 at address 0x6a. Got -20001.
	at com.pi4j.io.i2c.impl.I2CDeviceImpl.write(I2CDeviceImpl.java:81)
	at net.happybrackets.device.sensors.LSM9DS1.read(LSM9DS1.java:301)
	at net.happybrackets.device.sensors.LSM9DS1.disableGyroscope(LSM9DS1.java:593)
	at net.happybrackets.device.sensors.LSM9DS1.enableGyroscope(LSM9DS1.java:571)
	at net.happybrackets.device.sensors.LSM9DS1.<init>(LSM9DS1.java:258)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at net.happybrackets.device.HB.getSensor(HB.java:717)
	at net.happybrackets.develop.DeviceMonitor.AcelerometerSend.action(AcelerometerSend.java:68)
	at net.happybrackets.device.HB$3.run(HB.java:675)
ERROR net.happybrackets.device.sensors.LSM9DS1 - Unable to write to I2C device
java.io.IOException: Error writing to /dev/i2c-1 at address 0x6a to address 0x10. Got -20001.
	at com.pi4j.io.i2c.impl.I2CDeviceImpl.write(I2CDeviceImpl.java:147)
	at net.happybrackets.device.sensors.LSM9DS1.write(LSM9DS1.java:343)
	at net.happybrackets.device.sensors.LSM9DS1.disableGyroscope(LSM9DS1.java:596)
	at net.happybrackets.device.sensors.LSM9DS1.enableGyroscope(LSM9DS1.java:571)
	at net.happybrackets.device.sensors.LSM9DS1.<init>(LSM9DS1.java:258)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at net.happybrackets.device.HB.getSensor(HB.java:717)
	at net.happybrackets.develop.DeviceMonitor.AcelerometerSend.action(AcelerometerSend.java:68)
	at net.happybrackets.device.HB$3.run(HB.java:675)
ACCTest 0 0 reg 16 value 105
ERROR net.happybrackets.device.sensors.LSM9DS1 - Unable to write to I2C device
java.io.IOException: Error writing to /dev/i2c-1 at address 0x6a to address 0x10. Got -20001.
	at com.pi4j.io.i2c.impl.I2CDeviceImpl.write(I2CDeviceImpl.java:124)
	at net.happybrackets.device.sensors.LSM9DS1.write(LSM9DS1.java:324)
	at net.happybrackets.device.sensors.LSM9DS1.enableGyroscope(LSM9DS1.java:574)
	at net.happybrackets.device.sensors.LSM9DS1.<init>(LSM9DS1.java:258)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at net.happybrackets.device.HB.getSensor(HB.java:717)
	at net.happybrackets.develop.DeviceMonitor.AcelerometerSend.action(AcelerometerSend.java:68)
	at net.happybrackets.device.HB$3.run(HB.java:675)
ACCTest 0 0 reg 18 value 68
ERROR net.happybrackets.device.sensors.LSM9DS1 - Unable to write to I2C device
java.io.IOException: Error writing to /dev/i2c-1 at address 0x6a to address 0x12. Got -20001.
	at com.pi4j.io.i2c.impl.I2CDeviceImpl.write(I2CDeviceImpl.java:124)
	at net.happybrackets.device.sensors.LSM9DS1.write(LSM9DS1.java:324)
	at net.happybrackets.device.sensors.LSM9DS1.enableGyroscope(LSM9DS1.java:576)
	at net.happybrackets.device.sensors.LSM9DS1.<init>(LSM9DS1.java:258)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at net.happybrackets.device.HB.getSensor(HB.java:717)
	at net.happybrackets.develop.DeviceMonitor.AcelerometerSend.action(AcelerometerSend.java:68)
	at net.happybrackets.device.HB$3.run(HB.java:675)
MagTest 1 1 reg 34 value 3
ERROR net.happybrackets.device.sensors.LSM9DS1 - Unable to write to I2C device
java.io.IOException: Error writing to /dev/i2c-1 at address 0x1c to address 0x22. Got -20001.
	at com.pi4j.io.i2c.impl.I2CDeviceImpl.write(I2CDeviceImpl.java:124)
	at net.happybrackets.device.sensors.LSM9DS1.write(LSM9DS1.java:327)
	at net.happybrackets.device.sensors.LSM9DS1.disableMagnetometer(LSM9DS1.java:628)
	at net.happybrackets.device.sensors.LSM9DS1.enableMagnetometer(LSM9DS1.java:607)
	at net.happybrackets.device.sensors.LSM9DS1.<init>(LSM9DS1.java:260)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at net.happybrackets.device.HB.getSensor(HB.java:717)
	at net.happybrackets.develop.DeviceMonitor.AcelerometerSend.action(AcelerometerSend.java:68)
	at net.happybrackets.device.HB$3.run(HB.java:675)
MagTest 1 1 reg 32 value 20
ERROR net.happybrackets.device.sensors.LSM9DS1 - Unable to write to I2C device
java.io.IOException: Error writing to /dev/i2c-1 at address 0x1c to address 0x20. Got -20001.
	at com.pi4j.io.i2c.impl.I2CDeviceImpl.write(I2CDeviceImpl.java:124)
	at net.happybrackets.device.sensors.LSM9DS1.write(LSM9DS1.java:327)
	at net.happybrackets.device.sensors.LSM9DS1.enableMagnetometer(LSM9DS1.java:610)
	at net.happybrackets.device.sensors.LSM9DS1.<init>(LSM9DS1.java:260)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at net.happybrackets.device.HB.getSensor(HB.java:717)
	at net.happybrackets.develop.DeviceMonitor.AcelerometerSend.action(AcelerometerSend.java:68)
	at net.happybrackets.device.HB$3.run(HB.java:675)
MagTest 1 1 reg 33 value 0

**Comment by angelofraietta** [comment]
Fixed in 1.15.7. We prevent thread from starting if the sensor is not connected
