### ISSUE TITLE
resending the same class file to device causes exception

### ISSUE THREAD

**Issue by samgwise** [orsjb/HappyBrackets#6]
Exception in thread "Thread-6" java.lang.LinkageError: loader (instance of  net/happybrackets/device/dynamic/DynamicClassLoader): attempted  duplicate class definition for name: "net/happybrackets/tutorial/session1/CodeTask1_1"
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
        at net.happybrackets.device.dynamic.DynamicClassLoader.createNewClass(DynamicClassLoader.java:15)
        at net.happybrackets.device.HB$2.run(HB.java:209)

**Comment by orsjb** [comment]
Resolved. Basically this only happens if you're trying to send something that is not an HBAction to the Pi (which you shouldn't be doing). The classloader has to be recreated in order to reload classes with the same ID, but you don't want to recreate if everytime you send a class over. So what we do is we reset the classloader every time an HBAction arrives, and we also properly deal with the error now.
