### ISSUE TITLE
Freezing of Intellij When loading with a wireless network

### ISSUE THREAD

**Issue by angelofraietta** [orsjb/HappyBrackets#72]
It appears that IntelliJ sometimes freezes if wifi is enabled and there is a project bing loaded. It only seems to occur when the toolwindow is opening.  Examining logs shows

`"AWT-EventQueue-0 2018.1.5#IC-181.5281.24 IDEA, eap:false, os:Mac OS X 10.13.5, java-version:JetBrains s.r.o 1.8.0_152-release-1136-b39" prio=0 tid=0x0 nid=0x0 runnable
     java.lang.Thread.State: RUNNABLE
 (in native)
	at java.net.Inet4AddressImpl.getHostByAddr(Native Method)
	at java.net.InetAddress$2.getHostByAddr(InetAddress.java:932)
	at java.net.InetAddress.getHostFromNameService(InetAddress.java:617)
	at java.net.InetAddress.getHostName(InetAddress.java:559)
	at java.net.InetAddress.getHostName(InetAddress.java:531)
	at de.sciss.net.OSCReceiver.getLocalAddress(OSCReceiver.java:897)
	at de.sciss.net.OSCReceiver$UDPOSCReceiver.getLocalAddress(OSCReceiver.java:981)
	at de.sciss.net.OSCServer$UDPOSCServer.getLocalAddress(OSCServer.java:586)
	at net.happybrackets.controller.network.DeviceConnection.<init>(DeviceConnection.java:203)
	at net.happybrackets.controller.ControllerEngine.setControllerConfig(ControllerEngine.java:108)
	at net.happybrackets.intellij_plugin.HappyBracketsToolWindow.setConfig(HappyBracketsToolWindow.java:262)
	at net.happybrackets.intellij_plugin.HappyBracketsToolWindow.loadSingletons(HappyBracketsToolWindow.java:201)
	at `

**Comment by angelofraietta** [comment]
[threadDumps-freeze-20180621-133857-IC-181.5281.24.zip](https://github.com/orsjb/HappyBrackets/files/2122118/threadDumps-freeze-20180621-133857-IC-181.5281.24.zip)
This is a log showing freezing

We should possibly disable all network when toolwindow is first displayed, and when it loads up, then we look at doing network connection
